// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview A mobile HR bot that allows employees to request leave, payslips, and track job application status.
 *
 * - mobileHrBot - A function that handles the mobile HR bot requests.
 * - MobileHrBotInput - The input type for the mobileHrBot function.
 * - MobileHrBotOutput - The return type for the mobileHrBot function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const MobileHrBotInputSchema = z.object({
  employeeId: z.string().describe('The employee ID.'),
  requestType: z
    .enum(['leave', 'payslip', 'jobApplicationStatus'])
    .describe('The type of request.'),
  details: z
    .string()
    .optional()
    .describe('Additional details for the request.'),
});
export type MobileHrBotInput = z.infer<typeof MobileHrBotInputSchema>;

const MobileHrBotOutputSchema = z.object({
  response: z.string().describe('The response to the employee request.'),
});
export type MobileHrBotOutput = z.infer<typeof MobileHrBotOutputSchema>;

export async function mobileHrBot(input: MobileHrBotInput): Promise<MobileHrBotOutput> {
  return mobileHrBotFlow(input);
}

const prompt = ai.definePrompt({
  name: 'mobileHrBotPrompt',
  input: {schema: MobileHrBotInputSchema},
  output: {schema: MobileHrBotOutputSchema},
  prompt: `You are a helpful HR assistant bot for mobile/WhatsApp.

  Your job is to process employee requests related to leave, payslips, and job application status.
  You should respond in a clear and concise manner.

  Employee ID: {{{employeeId}}}
  Request Type: {{{requestType}}}
  Details: {{{details}}}

  Response:`,
});

const mobileHrBotFlow = ai.defineFlow(
  {
    name: 'mobileHrBotFlow',
    inputSchema: MobileHrBotInputSchema,
    outputSchema: MobileHrBotOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
