
-- Create custom enum types for status fields to ensure data consistency.

CREATE TYPE applicant_status AS ENUM ('New', 'Pending Review', 'Interview Scheduled', 'Rejected', 'Offer Extended');
CREATE TYPE assessment_type AS ENUM ('aptitude', 'typing');
CREATE TYPE assessment_status AS ENUM ('assigned', 'completed');
CREATE TYPE job_status AS ENUM ('Accepting Applications', 'Screening', 'Interviewing', 'Offer Extended', 'Closed');
CREATE TYPE college_status AS ENUM ('Invited', 'Confirmed', 'Screening', 'Scheduled');
CREATE TYPE employee_work_status AS ENUM ('Remote', 'Office', 'Leave', 'Probation');
CREATE TYPE document_type AS ENUM ('Policy', 'Training', 'Manual');
CREATE TYPE document_status AS ENUM ('Active', 'Draft', 'Archived');
CREATE TYPE grievance_category AS ENUM ('Payroll', 'Facilities', 'Interpersonal', 'Policy', 'Feedback', 'Other');
CREATE TYPE grievance_status AS ENUM ('Open', 'In Progress', 'Resolved', 'Closed');
CREATE TYPE grievance_responder AS ENUM ('HR', 'Legal');

-- Table for Job Applicants
CREATE TABLE applicants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    full_name TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    phone TEXT,
    resume_text TEXT,
    status applicant_status DEFAULT 'New',
    role TEXT,
    source TEXT,
    college TEXT,
    hr_notes TEXT,
    avatar_url TEXT,
    resume_summary TEXT
);
ALTER TABLE applicants ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public applicants are viewable by everyone." ON applicants FOR SELECT USING (true);
CREATE POLICY "Users can insert their own applicants." ON applicants FOR INSERT WITH CHECK (true);


-- Table for Assessments (Aptitude, Typing, etc.)
CREATE TABLE assessments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    applicant_id BIGINT REFERENCES applicants(id) ON DELETE CASCADE,
    test_type assessment_type NOT NULL,
    status assessment_status DEFAULT 'assigned',
    score TEXT, -- Can store "4/5" or a percentage
    wpm INTEGER,
    accuracy INTEGER,
    test_data JSONB -- To store generated questions or typing text
);
ALTER TABLE assessments ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Assessments are viewable by everyone." ON assessments FOR SELECT USING (true);
CREATE POLICY "Users can insert assessments." ON assessments FOR INSERT WITH CHECK (true);


-- Table for Job Postings
CREATE TABLE jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    title TEXT NOT NULL,
    department TEXT,
    location TEXT,
    source TEXT,
    status job_status DEFAULT 'Accepting Applications',
    description TEXT,
    applicants_count INTEGER DEFAULT 0
);
ALTER TABLE jobs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Jobs are viewable by everyone." ON jobs FOR SELECT USING (true);


-- Table for Campus HR
CREATE TABLE colleges (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    name TEXT NOT NULL,
    location TEXT,
    contact_email TEXT,
    status college_status DEFAULT 'Invited',
    resumes_received INTEGER DEFAULT 0
);
ALTER TABLE colleges ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Colleges are viewable by everyone." ON colleges FOR SELECT USING (true);


-- Table for Employees
CREATE TABLE employees (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    name TEXT NOT NULL,
    role TEXT,
    status employee_work_status DEFAULT 'Office',
    avatar_url TEXT,
    email TEXT UNIQUE NOT NULL
);
ALTER TABLE employees ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Employees are viewable by everyone." ON employees FOR SELECT USING (true);


-- Table for Compliance Documents
CREATE TABLE documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    name TEXT NOT NULL,
    type document_type,
    version TEXT,
    status document_status DEFAULT 'Draft',
    expiry_date DATE,
    acknowledgement_percentage INTEGER DEFAULT 0
);
ALTER TABLE documents ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Documents are viewable by everyone." ON documents FOR SELECT USING (true);


-- Table for Grievances
CREATE TABLE grievances (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id TEXT UNIQUE NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    title TEXT NOT NULL,
    description TEXT,
    category grievance_category,
    is_anonymous BOOLEAN DEFAULT false,
    status grievance_status DEFAULT 'Open',
    assigned_to grievance_responder,
    submitter_id BIGINT REFERENCES employees(id) ON DELETE SET NULL
);
ALTER TABLE grievances ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Grievances are viewable by everyone." ON grievances FOR SELECT USING (true);


-- Table for Predictive Analytics Data
CREATE TABLE analytics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    "attritionPrediction" TEXT,
    "burnoutHeatmap" TEXT,
    "salaryBenchmarks" TEXT,
    "keyInsights" TEXT
);
ALTER TABLE analytics ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Analytics data is viewable by everyone." ON analytics FOR SELECT USING (true);
CREATE POLICY "Users can insert analytics data." ON analytics FOR INSERT WITH CHECK (true);
